export const data = [{
    "id": 1,
    "first_name": "Osborne",
    "last_name": "Howen"
  }, {
    "id": 2,
    "first_name": "Cosetta",
    "last_name": "Di Francesco"
  }, {
    "id": 3,
    "first_name": "Cherlyn",
    "last_name": "Gaishson"
  }, {
    "id": 4,
    "first_name": "Lauren",
    "last_name": "Philcott"
  }, {
    "id": 5,
    "first_name": "Jolee",
    "last_name": "Brazer"
  }, {
    "id": 6,
    "first_name": "Goldy",
    "last_name": "Stening"
  }, {
    "id": 7,
    "first_name": "Salmon",
    "last_name": "Niblo"
  }, {
    "id": 8,
    "first_name": "Agnes",
    "last_name": "Bootton"
  }, {
    "id": 9,
    "first_name": "Bron",
    "last_name": "Larne"
  }, {
    "id": 10,
    "first_name": "Lilah",
    "last_name": "Lampet"
  }, {
    "id": 11,
    "first_name": "Keen",
    "last_name": "Corness"
  }, {
    "id": 12,
    "first_name": "Dalston",
    "last_name": "MacGillivray"
  }, {
    "id": 13,
    "first_name": "Doro",
    "last_name": "Ternent"
  }, {
    "id": 14,
    "first_name": "Laurena",
    "last_name": "Guerreau"
  }, {
    "id": 15,
    "first_name": "Berkly",
    "last_name": "Daniels"
  }, {
    "id": 16,
    "first_name": "Casey",
    "last_name": "Josham"
  }, {
    "id": 17,
    "first_name": "Evie",
    "last_name": "Hryncewicz"
  }, {
    "id": 18,
    "first_name": "Caterina",
    "last_name": "Boorn"
  }, {
    "id": 19,
    "first_name": "Raina",
    "last_name": "Raddon"
  }, {
    "id": 20,
    "first_name": "Christophe",
    "last_name": "Ragbourn"
  }, {
    "id": 21,
    "first_name": "Wilmette",
    "last_name": "Ianniello"
  }, {
    "id": 22,
    "first_name": "Gleda",
    "last_name": "Espine"
  }, {
    "id": 23,
    "first_name": "Aldous",
    "last_name": "Reddie"
  }, {
    "id": 24,
    "first_name": "Jillene",
    "last_name": "Bytheway"
  }, {
    "id": 25,
    "first_name": "Garnet",
    "last_name": "Nicolls"
  }, {
    "id": 26,
    "first_name": "Brunhilde",
    "last_name": "Toten"
  }, {
    "id": 27,
    "first_name": "Domenico",
    "last_name": "Measures"
  }, {
    "id": 28,
    "first_name": "Emelyne",
    "last_name": "Feldmark"
  }, {
    "id": 29,
    "first_name": "Geoffrey",
    "last_name": "Cote"
  }, {
    "id": 30,
    "first_name": "Ingmar",
    "last_name": "Pancoast"
  }, {
    "id": 31,
    "first_name": "Janek",
    "last_name": "Painten"
  }, {
    "id": 32,
    "first_name": "Nefen",
    "last_name": "Gething"
  }, {
    "id": 33,
    "first_name": "Claudia",
    "last_name": "Dovermann"
  }, {
    "id": 34,
    "first_name": "Moselle",
    "last_name": "McGilben"
  }, {
    "id": 35,
    "first_name": "Terry",
    "last_name": "Templeton"
  }, {
    "id": 36,
    "first_name": "Bernita",
    "last_name": "Flury"
  }, {
    "id": 37,
    "first_name": "Leonid",
    "last_name": "Merrick"
  }, {
    "id": 38,
    "first_name": "Neely",
    "last_name": "Pencott"
  }, {
    "id": 39,
    "first_name": "El",
    "last_name": "Campa"
  }, {
    "id": 40,
    "first_name": "Aguste",
    "last_name": "Piatek"
  }, {
    "id": 41,
    "first_name": "Tiertza",
    "last_name": "Snedker"
  }, {
    "id": 42,
    "first_name": "Evonne",
    "last_name": "Macartney"
  }, {
    "id": 43,
    "first_name": "Freemon",
    "last_name": "Ropkins"
  }, {
    "id": 44,
    "first_name": "James",
    "last_name": "Weathers"
  }, {
    "id": 45,
    "first_name": "Jo",
    "last_name": "Mosey"
  }, {
    "id": 46,
    "first_name": "Richie",
    "last_name": "Preator"
  }, {
    "id": 47,
    "first_name": "Charmian",
    "last_name": "Salliss"
  }, {
    "id": 48,
    "first_name": "Regina",
    "last_name": "Shipp"
  }, {
    "id": 49,
    "first_name": "El",
    "last_name": "Martinson"
  }, {
    "id": 50,
    "first_name": "Erhart",
    "last_name": "Tarry"
  }]